import { Saira } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Providers } from "./providers";
import Layout from "./components/Layout";
import LanguageProvider from "./context/LanguageContext";

const inter = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "Ai Supervision",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${inter.className} bg-[#050505]  min-h-[100vh] `}>
        <Providers>
        <LanguageProvider>
          <Layout>
            {children}
          </Layout>
        </LanguageProvider>
        </Providers>
       
      </body>
    </html>
  );
}
