import { Saira } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Providers } from "./providers";
import Layout from "./components/Layout";
import LanguageProvider from "./context/LanguageContext";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import Head from 'next/head';

const inter = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "Ai Supervision",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,  params: {locale} }) {
  const messages = await getMessages();
  return (
    <html lang={locale} >
       <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body suppressHydrationWarning={true} className={`${inter.className} bg-[#050505]  min-h-[100vh] `}>
      <NextIntlClientProvider messages={messages}>
        <Providers>
        <LanguageProvider>
          <Layout>
            {children}
          </Layout>
        </LanguageProvider>
        </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
